#cloud-config
package_upgrade: true
packages:
  - apache2

write_files:
  - path: /var/www/html/index.html
    content: |
      <html>
      <body>
      <h1>Hello, World!</h1>
      </body>
      </html>
    owner: www-data:www-data

runcmd:
  - systemctl enable apache2
  - systemctl start apache2