name: Create Release

on:
  push:
    branches:
      - main

jobs:
    release:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
        - name: Checkout code
          uses: actions/checkout@v4.1.1

        - name: New Release/tags
          id: tag_version
          uses: mathieudutour/github-tag-action@v6.1
          with:
            dry_run: False
            default_bump: patch
            default_prerelease_bump: prerelease
            release_branches: main,master,maintest
            github_token: ${{ secrets.GITHUB_TOKEN }}

        - name: Release info
          run: |
            echo new tag: ${{ steps.tag_version.outputs.new_tag }}
            echo new version: ${{ steps.tag_version.outputs.new_version }}
            echo previous tag: ${{ steps.tag_version.outputs.previous_tag }}
            echo previous version: ${{ steps.tag_version.outputs.previous_version }}
            echo release type: ${{ steps.tag_version.outputs.release_type }}

        - name: Create Release
          uses: softprops/action-gh-release@v1
          with:
            name: Release ${{ steps.tag_version.outputs.new_version }}
            tag_name: ${{ steps.tag_version.outputs.new_version }}
            generate_release_notes: True
